### ISSUE TITLE
h5py distribution was not found

### ISSUE THREAD

**Issue by EricMei542** [NutritionalLungImmunity/simulation-framework#12]
An error raises while running the code: pkg_resources.DistributionNotFound:  The 'h5py' distribution was not found and is required by simulation

h5py package is not included in Pipfile.lock. Might that be the reason?

**Comment by jbeezley** [comment]
Yes, I should have updated the lockfile when I added h5py.  (You will still need to run `pipenv sync` to get the updates.)
