### ISSUE TITLE
Diffusion method outputs negative values

### ISSUE THREAD

**Issue by EricMei542** [NutritionalLungImmunity/simulation-framework#45]
I ran some tests on the diffusion method ```apply_diffusion``` and noted that some elements in the output matrix are negative.

For instance, I initialized a single-point resource on the surfactant with 1000 units (e.g the range of the value in the grid is [0, 1000]. One voxel is initialized as 1000, others 0). After 10 iterations, the data range of the grid becomes [-9.33833e-11, 9.72554]. Some elements turn negative, slightly below 0. I am not quite sure if this is because there is some noise when we are computing the diffusion by the Laplacian matrix or I did something wrong.

**Comment by jbeezley** [comment]
That sounds like expected rounding error to me.  If the diffusion is expected to be executed on non-negative variables, we can truncate the result (e.g. `a[a < 0] = 0`).

**Comment by EricMei542** [comment]
I see. I will not modify the diffusion function for now. We can truncate the result if necessary in the future. I will add a comment within the ```apply_diffusion``` docstring.
